:Author: deespider
:Email: {diptendu.biswas143@gmail.com}
:Date: 27/05/2020
:Revision: version#
:License: Public Domain

= Project: IoT SmartParking

Describe your project: In this parking system the user will get notified if there is an empty parking space available for parking.

== Step 1: Installation
Please describe the steps to install this project.

For example:

1. Open this file
2. Edit as you like
3. Release to the World!

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 iotparking               => Arduino sketch folder
  ├── smartparking.ino    => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact deespider https://id.arduino.cc/deespider

=== BOM
Add the bill of the materials you need for this project.

|===
| Part name                | Part number | Quantity
| IR Transreciver Sensor   |             | 4
| USB Type B Cable         |             | 5
| Node MCU                 | ESP8266 12E | 1
| Bread Board              |             | 1
| Jumper Wires             |             | 10
|===

